# Generated by Django 5.1.6 on 2025-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('home_country', models.CharField(blank=True, max_length=100, null=True)),
                ('home_city', models.CharField(blank=True, max_length=100, null=True)),
                ('home_lat', models.DecimalField(decimal_places=6, default=23.076099, max_digits=9)),
                ('home_long', models.DecimalField(decimal_places=6, default=72.508408, max_digits=9)),
                ('default_device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('risk_Score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
