# Generated by Django 5.1.6 on 2025-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetLoginRecord',
            fields=[
                ('login_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('asn', models.CharField(blank=True, max_length=50, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=23.076099, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=72.508408, max_digits=9)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot')], db_index=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('login_success', models.BooleanField(db_index=True, default=False)),
                ('ip_reputation', models.CharField(choices=[('0', 'normal'), ('1', 'suspicious'), ('2', 'blacklisted')], db_index=True, default='0', max_length=2)),
                ('is_vpn_tor', models.BooleanField(db_index=True, default=False)),
                ('num_distinct_devices_last30d', models.PositiveIntegerField(default=0)),
                ('failed_attempts_last_10m', models.PositiveIntegerField(default=0)),
                ('hours_since_prev_login', models.FloatField(blank=True, null=True)),
                ('distance_from_prev_login_km', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('prediction', models.CharField(choices=[('normal', 'normal'), ('anomalous', 'anomalous')], db_index=True, default='normal', max_length=20)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('reason', models.JSONField(blank=True, help_text="List of reasons / contributing features (e.g., ['New device','Geo mismatch'])", null=True)),
            ],
        ),
    ]
